######################################################################
# Automatically generated by qmake (3.0) Mon Aug 27 15:11:41 2018
######################################################################

TEMPLATE = app
TARGET = form
INCLUDEPATH += .

QT +=widgets

# Input
HEADERS += inputform.h
SOURCES += inputform.cpp inputFromTest.cpp
