######################################################################
# Automatically generated by qmake (3.0) Mon Aug 27 12:33:17 2018
######################################################################

TEMPLATE = app
TARGET = modal
INCLUDEPATH += .

QT +=widgets

# Input
SOURCES += main.cpp
